language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose

after_success: |
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"